AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'query-ap Sample SAM Template for query-api

  '
Parameters:
  DynamoEndpoint:
    Type: String
    Default: cloud
    AllowedValues:
    - http://dynamo-local:8000
    - cloud
    Description: http://dynamo-local:8000, cloud
Globals:
  Function:
    Timeout: 3
Resources:
  ProductsQueryApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: ProductsAPI
      DefinitionUri: s3://dakobed-serverless-apis/95fda7828f05ff484a41c65780734859
  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetCategoriesFunction
      CodeUri: s3://dakobed-serverless-apis/a62fe191ff911fcde76553107f815a71
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint:
            Ref: DynamoEndpoint
      Policies:
      - DynamoDBReadPolicy:
          TableName: Categories
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: ProductsQueryApi
            Path: /categories
            Method: get
  VendorQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: VendorQueryFunction
      CodeUri: s3://dakobed-serverless-apis/6ef9ef7d216ea1e320dae2da1fffde30
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint:
            Ref: DynamoEndpoint
      Policies:
      - DynamoDBReadPolicy:
          TableName: Products
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: ProductsQueryApi
            Path: /products/vendor/{vendor_id}
            Method: get
  CategoryQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CategoryQueryFunction
      CodeUri: s3://dakobed-serverless-apis/a496951e27616cf037b6cbd283535e8c
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint:
            Ref: DynamoEndpoint
      Policies:
      - DynamoDBReadPolicy:
          TableName: Products
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: ProductsQueryApi
            Path: /products/category/{category}
            Method: get
  VendorCategoryQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: VendorCategoryQueryFunction
      CodeUri: s3://dakobed-serverless-apis/28dae270df2608e28b3ca743f03ee422
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint:
            Ref: DynamoEndpoint
      Policies:
      - DynamoDBReadPolicy:
          TableName: Products
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: ProductsQueryApi
            Path: /products/vendor/{vendor}/{category}
            Method: get
  ProductsScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ProductsScanFunction
      CodeUri: s3://dakobed-serverless-apis/b4c5ec891a6d9aed71bed550181d5580
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
      - DynamoDBReadPolicy:
          TableName: Products
      Events:
        ProductsQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: ProductsQueryApi
            Path: /products
            Method: get
