AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'query-ap Sample SAM Template for query-api

  '
Globals:
  Function:
    Timeout: 3
Resources:
  ProductsQueryApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: ProductsAPI
      DefinitionUri: s3://dakobed-serverless-apis/50bb6b8a826028e9588fe39d4f6eb636
  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetCategoriesFunction
      CodeUri: s3://dakobed-serverless-apis/3ae08edb2f32f1b1b2536a8b10f3d195
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
      - DynamoDBReadPolicy:
          TableName: Categories
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: ProductsQueryApi
            Path: /categories
            Method: get
  VendorQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: VendorQueryFunction
      CodeUri: s3://dakobed-serverless-apis/71918acce8ac572ab25252231fcd72bb
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
      - DynamoDBReadPolicy:
          TableName: Products
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: ProductsQueryApi
            Path: /products/vendor/{vendor_id}
            Method: get
  CategoryQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CategoryQueryFunction
      CodeUri: s3://dakobed-serverless-apis/5b9b80e7beede7a43b8bc7bce1c3e118
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
      - DynamoDBReadPolicy:
          TableName: Products
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: ProductsQueryApi
            Path: /products/category/{category}
            Method: get
  VendorCategoryQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: VendorCategoryQueryFunction
      CodeUri: s3://dakobed-serverless-apis/e63d7e21f84d0d5cd147bcd0da1b91a6
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
      - DynamoDBReadPolicy:
          TableName: Products
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: ProductsQueryApi
            Path: /products/vendor/{vendor}/{category}
            Method: get
