AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  query-ap
  Sample SAM Template for query-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Parameters:
  DynamoEndpoint:
    Type: String
    Default: cloud
    AllowedValues:
      - http://dynamo-local:8000
      - cloud
    Description: http://dynamo-local:8000, cloud


Globals:
  Function:
    Timeout: 3

Resources:
  ProductsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: ProductsApi
      DefinitionUri: ./swagger.yaml

  GetCategoriesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: GetCategoriesFunction
      CodeUri: handlers/get_categories/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint: !Ref DynamoEndpoint

      Policies:
        - DynamoDBReadPolicy:
            TableName: Categories
      Events:
        VendorQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProductsApi
            Path: /categories
            Method: get

  VendorQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: VendorQueryFunction
      CodeUri: handlers/query_vendor/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint: !Ref DynamoEndpoint
      Policies:
        - DynamoDBReadPolicy:
            TableName: Products
      Events:
        VendorQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProductsApi
            Path: /products/vendor/{vendor_id}
            Method: get


  CategoryQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: CategoryQueryFunction
      CodeUri: handlers/query_category/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint: !Ref DynamoEndpoint
      Policies:
        - DynamoDBReadPolicy:
            TableName: Products
      Events:
        VendorQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProductsApi
            Path: /products/category/{category}
            Method: get

  VendorCategoryQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: VendorCategoryQueryFunction
      CodeUri: handlers/query_category_vendor/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint: !Ref DynamoEndpoint
      Policies:
        - DynamoDBReadPolicy:
            TableName: Products
      Events:
        VendorQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProductsApi
            Path: /products/vendor/{vendor}/{category}
            Method: get


  ProductsScanFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: ProductsScanFunction
      CodeUri: handlers/scan_products/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - DynamoDBReadPolicy:
            TableName: Products
      Events:
        ProductsQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProductsApi
            Path: /products
            Method: get

  ProductDetailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: ProductDetailFunction
      CodeUri: handlers/product_detail/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - DynamoDBReadPolicy:
            TableName: Products
      Events:
        ProductsQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProductsApi
            Path: /products/{vendor}/{productName}
            Method: get

Outputs:
  ProductsApi:
    Value: !Sub "https://${ProductsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'ProductsApi' ] ]



#Outputs:
#  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#  # Find out more about other implicit resources you can reference within SAM
#  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  ProductsQueryApi:
#    Description: "API Gateway endpoint URL for Prod stage for ProductsQueryFunction"
#    Value: !Sub "https://${ProductsQueryApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/products/"
#  ProductsScanFunction:
#    Description: "Hello World Lambda Function ARN"
#    Value: !GetAtt ProductsScanFunction.Arn
#  HelloWorldFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt ProductsScanFunction.Arn
