AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  query-ap
  Sample SAM Template for query-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Parameters:
  DynamoEndpoint:
    Type: String
    Default: cloud
    AllowedValues:
      - http://dynamo-local:8000
      - cloud
    Description: http://dynamo-local:8000, cloud


Globals:
  Function:
    Timeout: 3

Resources:
  ProductsQueryApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: ProductsAPI
      DefinitionUri: ./swagger.yaml

  GetCategoriesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: GetCategoriesFunction
      CodeUri: get_categories/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint: !Ref DynamoEndpoint

      Policies:
        - DynamoDBReadPolicy:
            TableName: Categories
      Events:
        VendorQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProductsQueryApi
            Path: /categories
            Method: get

  VendorQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: VendorQueryFunction
      CodeUri: query_vendor/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint: !Ref DynamoEndpoint
      Policies:
        - DynamoDBReadPolicy:
            TableName: Products
      Events:
        VendorQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProductsQueryApi
            Path: /products/vendor/{vendor_id}
            Method: get


  CategoryQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: CategoryQueryFunction
      CodeUri: query_category/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint: !Ref DynamoEndpoint
      Policies:
        - DynamoDBReadPolicy:
            TableName: Products
      Events:
        VendorQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProductsQueryApi
            Path: /products/category/{category}
            Method: get

  VendorCategoryQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: VendorCategoryQueryFunction
      CodeUri: query_category_vendor/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint: !Ref DynamoEndpoint
      Policies:
        - DynamoDBReadPolicy:
            TableName: Products
      Events:
        VendorQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProductsQueryApi
            Path: /products/vendor/{vendor}/{category}
            Method: get


#  ProductsScanFunction:
#    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#    Properties:
#      FunctionName: ProductsScanFunction
#      CodeUri: scan_products/
#      Handler: app.lambda_handler
#      Runtime: python3.7
#      Policies:
#        - DynamoDBReadPolicy:
#            TableName: Products
#      Events:
#        ProductsQuery:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            RestApiId: !Ref ProductsQueryApi
#            Path: /products
#            Method: get

#Outputs:
#  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#  # Find out more about other implicit resources you can reference within SAM
#  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  ProductsQueryApi:
#    Description: "API Gateway endpoint URL for Prod stage for ProductsQueryFunction"
#    Value: !Sub "https://${ProductsQueryApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/products/"
#  ProductsScanFunction:
#    Description: "Hello World Lambda Function ARN"
#    Value: !GetAtt ProductsScanFunction.Arn
#  HelloWorldFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt ProductsScanFunction.Arn
