AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  query-ap
  Sample SAM Template for query-api

Parameters:
  Region:
    Type: String
    Default: us-west-2

  DynamoEndpoint:
    Type: String
    Default: cloud
    AllowedValues:
      - http://dynamo-local:8000
      - cloud
    Description: http://dynamo-local:8000, cloud

Resources:
  CustomersAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: CustomersAPI
      DefinitionUri: ./swagger.yaml
      StageName: Prod

#  CustomerDetailFunction:
#    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#    Properties:
#      FunctionName: CustomerDetailFunction
#      CodeUri: handlers/customer_detail/
#      Layers:
#        - !ImportValue authorization-api-stack:AuthorizationLayer
#
#      Handler: app.lambda_handler
#      Runtime: python3.7
#      Environment:
#        Variables:
#          dynamo_endpoint: !Ref DynamoEndpoint
#          userpool_id: !ImportValue outdoorec-userpool-stack:UserPool
#          app_client_id: !ImportValue outdoorec-userpool-stack:UserPoolClient
#          region: !Ref Region
#
#      Policies:
#        - DynamoDBReadPolicy:
#            TableName: Customers
#      Events:
#        VendorQuery:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            RestApiId: !Ref CustomersAPI
#            Path: /customers/{customerID}
#            Method: get

  CreateCustomerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: CreateCustomerFunction
      CodeUri: handlers/create_customer/

      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint: !Ref DynamoEndpoint
          userpool_id: !ImportValue outdoorec-userpool-stack:UserPool
          app_client_id: !ImportValue outdoorec-userpool-stack:UserPoolClient
          region: !Ref Region

      Policies:
        - DynamoDBCrudPolicy:
            TableName: Customers
      Events:
        VendorQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref CustomersAPI
            Path: /customers/create/{customerID}
            Method: post


  VerifyCustomerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: VerifyCustomerFunction
      CodeUri: handlers/verify_customer/

      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint: !Ref DynamoEndpoint
          userpool_id: !ImportValue outdoorec-userpool-stack:UserPool
          app_client_id: !ImportValue outdoorec-userpool-stack:UserPoolClient
          region: !Ref Region

      Policies:
        - DynamoDBCrudPolicy:
            TableName: Customers
      Events:
        VendorQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref CustomersAPI
            Path: /customers/verify/{customerID}
            Method: post



