AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'query-ap Sample SAM Template for query-api

  '
Parameters:
  Region:
    Type: String
    Default: us-west-2
  DynamoEndpoint:
    Type: String
    Default: cloud
    AllowedValues:
    - http://dynamo-local:8000
    - cloud
    Description: http://dynamo-local:8000, cloud
Resources:
  OrdersAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: OrdersAPI
      DefinitionUri: s3://dakobed-serverless-apis/738002325ca8ccdc8263eec432715550
      StageName: Prod
  CustomersOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CustomersOrdersFunction
      CodeUri: s3://dakobed-serverless-apis/8f1b2569a2f2b011ef284b85876b9904
      Layers:
      - Fn::ImportValue: authorization-api-stack:AuthorizationLayer
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint:
            Ref: DynamoEndpoint
          userpool_id:
            Fn::ImportValue: ourdoorrec-customers-stack:UserPool
          app_client_id:
            Fn::ImportValue: ourdoorrec-customers-stack:UserPoolClient
          region:
            Ref: Region
      Policies:
      - DynamoDBReadPolicy:
          TableName: Orders
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: OrdersAPI
            Path: /orders
            Method: get
  PostOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostOrderFunction
      CodeUri: s3://dakobed-serverless-apis/74f58bd8c0086966dc7da8ea6c8e3c34
      Layers:
      - Fn::ImportValue: authorization-api-stack:AuthorizationLayer
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint:
            Ref: DynamoEndpoint
          userpool_id:
            Fn::ImportValue: ourdoorrec-customers-stack:UserPool
          app_client_id:
            Fn::ImportValue: ourdoorrec-customers-stack:UserPoolClient
          region:
            Ref: Region
      Policies:
      - DynamoDBCrudPolicy:
          TableName: Orders
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: OrdersAPI
            Path: /orders
            Method: post
Outputs:
  OrdersApi:
    Value:
      Fn::Sub: https://${OrdersAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod
    Export:
      Name:
        Fn::Join:
        - ':'
        - - Ref: AWS::StackName
          - OrdersAPI
