AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'query-ap Sample SAM Template for query-api

  '
Parameters:
  Region:
    Type: String
    Default: us-west-2
  DynamoEndpoint:
    Type: String
    Default: cloud
    AllowedValues:
    - http://dynamo-local:8000
    - cloud
    Description: http://dynamo-local:8000, cloud
Resources:
  OrdersAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: OrdersAPI
      DefinitionUri: s3://dakobed-serverless-apis/8293ca65d849974ef3caf91ea089f55d
      StageName: Prod
  CustomersOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CustomersOrdersFunction
      CodeUri: s3://dakobed-serverless-apis/fb4bd36bdb1e596b3ba34ea3822ee17d
      Layers:
      - Ref: AuthorizationLayer
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint:
            Ref: DynamoEndpoint
          userpool_id:
            Fn::ImportValue: outdoorec-userpool-stack:UserPool
          app_client_id:
            Fn::ImportValue: outdoorec-userpool-stack:UserPoolClient
          region:
            Ref: Region
      Policies:
      - DynamoDBReadPolicy:
          TableName: Orders
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: OrdersAPI
            Path: /orders/{customerID}
            Method: get
  PostOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostOrderFunction
      CodeUri: s3://dakobed-serverless-apis/fc870fe4d9bf690e7e701292926b7fd8
      Layers:
      - Ref: AuthorizationLayer
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint:
            Ref: DynamoEndpoint
          userpool_id:
            Fn::ImportValue: outdoorec-userpool-stack:UserPool
          app_client_id:
            Fn::ImportValue: outdoorec-userpool-stack:UserPoolClient
          region:
            Ref: Region
      Policies:
      - DynamoDBCrudPolicy:
          TableName: Orders
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: OrdersAPI
            Path: /orders/{customerID}
            Method: post
  AuthorizationLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: s3://dakobed-serverless-apis/3ff94234273672c11784c3fa6f8cc03f
      CompatibleRuntimes:
      - python3.7
    Metadata:
      BuildMethod: python3.7
