AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'query-ap Sample SAM Template for query-api

  '
Parameters:
  Region:
    Type: String
    Default: us-west-2
  DynamoEndpoint:
    Type: String
    Default: cloud
    AllowedValues:
    - http://dynamo-local:8000
    - cloud
    Description: http://dynamo-local:8000, cloud
Resources:
  OrdersAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: OrdersAPI
      StageName: Prod
      Cors: '''*'''
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn:
              Fn::ImportValue: outdoorec-userpool-stack:UserPoolARN
  CustomersOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CustomersOrdersFunction
      CodeUri: s3://dakobed-serverless-apis/2444d3643818968bcf11394bf0cfd3cd
      Layers:
      - Ref: AuthorizationLayer
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          dynamo_endpoint:
            Ref: DynamoEndpoint
          userpool_id:
            Fn::ImportValue: outdoorec-userpool-stack:UserPool
          app_client_id:
            Fn::ImportValue: outdoorec-userpool-stack:UserPoolClient
          region:
            Ref: Region
      Policies:
      - DynamoDBReadPolicy:
          TableName: Orders
      Events:
        VendorQuery:
          Type: Api
          Properties:
            RestApiId:
              Ref: OrdersAPI
            Path: /orders/{customerID}
            Method: get
  AuthorizationLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: s3://dakobed-serverless-apis/13f256f4d682f932214dcea804f214bc
      CompatibleRuntimes:
      - python3.7
    Metadata:
      BuildMethod: python3.7
